In [3]:
import pandas as pd
import numpy as np

In [2]:
!pip install pandas

  Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl.metadata (18 kB)
  Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Using cached pandas-2.0.3-cp38-cp38-win_amd64.whl (10.8 MB)
Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)


In [4]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(df.Message, df.spam, test_size=0.2)

In [10]:
!pip install scikit-learn

  Using cached scikit_learn-1.3.2-cp38-cp38-win_amd64.whl.metadata (11 kB)
  Using cached scipy-1.10.1-cp38-cp38-win_amd64.whl.metadata (58 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.3.2-cp38-cp38-win_amd64.whl (9.3 MB)
Using cached scipy-1.10.1-cp38-cp38-win_amd64.whl (42.2 MB)
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)


In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [20]:
X_train[:4]

3842    Howz pain.it will come down today.do as i said...
3576    And do you have any one that can teach me how ...
4394    RECPT 1/3. You have ordered a Ringtone. Your o...
4798    Santa calling! Would your little ones like a c...
Name: Message, dtype: object

In [21]:
type(y_train)

pandas.core.series.Series

In [22]:
y_train[:4]

3842    0
3576    0
4394    1
4798    1
Name: spam, dtype: int64

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_cv=v.fit_transform(X_train.values)
x_train_cv

<4457x7810 sparse matrix of type '<class 'numpy.int64'>'
	with 59347 stored elements in Compressed Sparse Row format>

In [26]:
x_train_cv.shape

(4457, 7810)

In [27]:
v.get_feature_names_out()[1000:1050]

array(['anything', 'anythingtomorrow', 'anytime', 'anyway', 'anyways',
       'anywhere', 'aom', 'apart', 'apartment', 'apes', 'apnt', 'apo',
       'apologetic', 'apologise', 'apologize', 'apology', 'app',
       'apparently', 'appeal', 'appear', 'applebees', 'apples',
       'application', 'apply', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaches', 'approaching',
       'appropriate', 'approve', 'approved', 'approx', 'apps', 'appt',
       'april', 'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arab',
       'arcade', 'ard', 'are', 'area', 'aren', 'arent'], dtype=object)

In [28]:
v.get_feature_names_out().shape

(7810,)

In [29]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [30]:
v.vocabulary_

{'howz': 3544,
 'pain': 5099,
 'it': 3781,
 'will': 7580,
 'come': 1905,
 'down': 2427,
 'today': 7010,
 'do': 2374,
 'as': 1083,
 'said': 5943,
 'ystrday': 7787,
 'ice': 3603,
 'and': 960,
 'medicine': 4450,
 'you': 7772,
 'have': 3380,
 'any': 991,
 'one': 4987,
 'that': 6883,
 'can': 1626,
 'teach': 6811,
 'me': 4434,
 'how': 3537,
 'to': 7003,
 'ship': 6163,
 'cars': 1667,
 'recpt': 5709,
 'ordered': 5029,
 'ringtone': 5857,
 'your': 7776,
 'order': 5028,
 'is': 3769,
 'being': 1307,
 'processed': 5498,
 'santa': 5966,
 'calling': 1614,
 'would': 7676,
 'little': 4179,
 'ones': 4988,
 'like': 4137,
 'call': 1602,
 'from': 3037,
 'xmas': 7717,
 'eve': 2666,
 '09077818151': 230,
 'book': 1426,
 'time': 6969,
 'calls1': 1617,
 '50ppm': 539,
 'last': 4046,
 '3mins': 459,
 '30s': 430,
 'www': 7707,
 'santacalling': 5967,
 'com': 1899,
 'hi': 3443,
 'juan': 3884,
 'im': 3637,
 'coming': 1911,
 'home': 3492,
 'on': 4982,
 'fri': 3014,
 'hey': 3440,
 'of': 4938,
 'course': 2039,
 'expect':

In [31]:
x_train_np=x_train_cv.toarray()
x_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
np.where(x_train_np[0]!=0)

(array([ 960, 1083, 1905, 2374, 2427, 3544, 3603, 3781, 4450, 5099, 5943,
        7010, 7580, 7787], dtype=int64),)

In [34]:
X_train[:4]

3842    Howz pain.it will come down today.do as i said...
3576    And do you have any one that can teach me how ...
4394    RECPT 1/3. You have ordered a Ringtone. Your o...
4798    Santa calling! Would your little ones like a c...
Name: Message, dtype: object

In [35]:
x_train_np[0][960]

1

In [37]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [39]:
X_test_cv=v.transform(X_test)

In [40]:
from sklearn.metrics import classification_report

y_pred=model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       976
           1       0.95      0.91      0.93       139

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [42]:
emails=[
    'hey mohan can we get together to watch football game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [43]:
from sklearn.pipeline import Pipeline

clf=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [44]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [45]:
y_pred=clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       976
           1       0.95      0.91      0.93       139

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115

